
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/customer2;AUTO_SERVER=true
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate
spring.thymeleaf.cache: false
spring.view.prefix: /WEB-INF/jsp/
spring.view.suffix: .jsp
spring.thymeleaf.prefix: classpath:/thymeleaf/
spring.thymeleaf.suffix:
spring.thymeleaf.viewNames: '*.html,*.xhtml'

security.basic.enabled: false
