spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:c:/tmp/customer4;AUTO_SERVER=true
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: validate
spring.thymeleaf.cache: false
security.basic.enabled: false
